package validator

const (
	required     = "required"
	alpha        = "alpha"
	alphaSpace   = "alphaSpace"
	alphaNumeric = "alphaNumeric"
	numeric      = "numeric"
	number       = "number"
	hexadecimal  = "hexadecimal"
	hexColor     = "hexColor"
	rgb          = "rgb"
	rgba         = "rgba"
	hsl          = "hsl"
	hsla         = "hsla"
	email        = "email"
	cron         = "cron"
	min          = "min"
	max          = "max"
	length       = "len"
	minLen       = "minLen"
	maxLen       = "maxLen"
	match        = "match"
	oneOf        = "oneOf"
	in           = "in"
	out          = "out"
	include      = "include"
	exclude      = "exclude"
)

const (
	typeString      = "string"
	typeStringPtr   = "*string"
	typeStringArray = "[]string"
	typeInt         = "int"
	typeIntPtr      = "*int"
	typeIntArray    = "[]int"
	typeUint        = "uint"
	typeUintPtr     = "*uint"
	typeUintArray   = "[]uint"
	typeFloat       = "float"
	typeFloatPtr    = "*float"
	typeFloatArray  = "[]float"
)
